CREATE OR REPLACE EDITIONABLE FUNCTION "KATERINA_BLZ"."GET_DAY"
RETURN VARCHAR2
IS
    v_day VARCHAR2(30);
BEGIN
    SELECT TO_CHAR(SYSDATE, 'DAY')
    INTO v_day
    FROM dual;

    RETURN v_day;
END get_day;
/
