
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "KATERINA_BLZ"."TOP_3_YOUNG_EMP" ("EMPLOYEE_ID", "FIRST_NAME", "LAST_NAME", "EMAIL", "PHONE_NUMBER", "HIRE_DATE", "JOB_ID", "SALARY", "COMMISSION_PCT", "MANAGER_ID", "DEPARTMENT_ID") AS 
  select *
from hr.employees
order by hire_date desc
fetch first 3 rows only;


  GRANT SELECT ON "KATERINA_BLZ"."TOP_3_YOUNG_EMP" TO "HR";
