CREATE OR REPLACE FORCE EDITIONABLE VIEW "KATERINA_BLZ"."TOP_3_YOUNG_EMP"
(
    "EMPLOYEE_ID",
    "FIRST_NAME",
    "LAST_NAME",
    "EMAIL",
    "PHONE_NUMBER",
    "HIRE_DATE",
    "JOB_ID",
    "SALARY",
    "COMMISSION_PCT",
    "MANAGER_ID",
    "DEPARTMENT_ID"
) AS
SELECT *
FROM hr.employees
ORDER BY hire_date DESC
FETCH FIRST 3 ROWS ONLY;
