CREATE OR REPLACE EDITIONABLE TRIGGER "KATERINA_BLZ"."HIRE_DATE_UPDATE"
BEFORE UPDATE ON employees
FOR EACH ROW
BEGIN
    IF :OLD.job_id != :NEW.job_id THEN
        :NEW.hire_date := TRUNC(SYSDATE);
    END IF;
END hire_date_update;
/

ALTER TRIGGER "KATERINA_BLZ"."HIRE_DATE_UPDATE" ENABLE;
