
  CREATE TABLE "KATERINA_BLZ"."DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER, 
	"DEPARTMENT_NAME" VARCHAR2(100 BYTE), 
	"BLOCK_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KATERINA_BLZ"."DEPARTMENTS"."DEPARTMENT_ID" IS 'ІД кафедри';
   COMMENT ON COLUMN "KATERINA_BLZ"."DEPARTMENTS"."DEPARTMENT_NAME" IS 'Назва кафедри';
   COMMENT ON COLUMN "KATERINA_BLZ"."DEPARTMENTS"."BLOCK_ID" IS 'ІД корпусу';

