
  CREATE TABLE "KATERINA_BLZ"."INTERBANK_INDEX_UA_HISTORY" 
   (	"DT" DATE, 
	"ID_API" VARCHAR2(100 BYTE), 
	"VALUE" NUMBER(10,4), 
	"SPECIAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

