
  CREATE TABLE "KATERINA_BLZ"."PROJECTS_EXT" 
   (	"PROJECT_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(200 BYTE), 
	"DEPARTMENT_ID" NUMBER
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "FILES_FROM_SERVER"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
        SKIP 1
        FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
        MISSING FIELD VALUES ARE NULL
    )
      LOCATION
       ( 'PROJECTS.csv'
       )
    )
   REJECT LIMIT UNLIMITED ;

