
  CREATE TABLE "KATERINA_BLZ"."STUDENTS" 
   (	"STUDENT_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"TEACHER_ID" NUMBER, 
	"START_DATE" DATE, 
	"FULL_NAME" VARCHAR2(100 BYTE), 
	"SCHOLARSHIP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."STUDENT_ID" IS 'ІД студента';
   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."DEPARTMENT_ID" IS 'ІД кафедри';
   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."TEACHER_ID" IS 'ІД викладача';
   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."START_DATE" IS 'Дата надходження';
   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."FULL_NAME" IS 'ПІБ студента';
   COMMENT ON COLUMN "KATERINA_BLZ"."STUDENTS"."SCHOLARSHIP" IS 'Стипендія студента';

